# Image for dagster-webserver and dagster-daemon. No pipeline code here;
# user code is loaded remotely via the gRPC server in Dockerfile_user_code.

FROM python:3.11-slim

RUN pip install --no-cache-dir \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
